services:
  web:
      build: .
      command: streamlit run ./main/app.py
      volumes:
        - .:/app
      ports:
        - "8501:8501"
      depends_on:
        - timescaledb
  timescaledb:
      image: timescale/timescaledb-ha:pg16
      container_name: timescaledb
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
      ports:
        - "5432:5432"
      volumes:
        - timescaledb_data:/var/lib/postgresql/data
      restart: unless-stopped

volumes:
  timescaledb_data: